In [ ]:
import numpy as np
import pandas as pd

In [ ]:
class Regresion:
  def __init__(self, df,nombre_Y,intercepto = True,Betas = True):
    
    self.df = df
    self.nombre_Y = nombre_Y
    self.intercepto = intercepto
    self.Betas = Betas

    a = 0
    for j in range(self.df.shape[1]):
      for i in self.df.index:
        if (str(type(self.df[self.df.columns[j]][i])) == "<class 'numpy.int64'>") or (str(type(self.df[self.df.columns[j]][i])) =="<class 'numpy.float64'>"):
          a += 1 
        else: 
          a = a
    
    if a == (self.df.shape[0]*self.df.shape[1]):
      None
    else:
      return print("Hay un error, el Data Frame tiene datos no numericos")
      

  def fit(self):
    if self.intercepto == True:
      Y = self.df[self.nombre_Y]
      Y = Y.to_numpy()
      X = self.df.drop([self.nombre_Y], axis = 1)
      X.insert(0,"Bo",1)
      X = X.to_numpy()
      self.betas = np.linalg.inv(np.transpose(X).dot(X)).dot(np.transpose(X)).dot(Y)
      return self.betas
    
    else:
      Y = self.df[self.nombre_Y]
      Y = Y.to_numpy()
      X = self.df.drop([self.nombre_Y], axis = 1)
      X = X.to_numpy()
      self.betas = np.linalg.inv(np.transpose(X).dot(X)).dot(np.transpose(X)).dot(Y)
      return self.betas

  def predict(self,valores_estimar):
    if self.intercepto == True:
      uno = np.array([1])
      valores_estimar = np.append(uno,valores_estimar)
      Y_estimado = valores_estimar.dot(np.transpose(self.betas))
      return Y_estimado
    else:
      Y_estimado = valores_estimar.dot(np.transpose(self.betas))
      return Y_estimado



In [ ]:
Dic = {"x":[1,2,3,4,5,6,7,8,9,10],
       "y":[28.4, 44.1, 57.2, 68.8,67.4, 82.0, 103.0, 114.6, 138.3, 147.6],
       "x_1":[1,2,4,4,5,6,7,7,9,10]} 

In [ ]:
Data = pd.DataFrame(Dic) 

In [ ]:
valores = np.array([2,3]) ; valores

array([2, 3])

In [ ]:
Modelo = Regresion(Data, "y", intercepto= False)

In [ ]:
Modelo.fit()

array([6.11986577, 8.93355705])

In [ ]:
Modelo.predict(valores)

39.04040268456329

In [ ]:
# Detectar errores

In [ ]:
Dic = {"x":[1,2,3,4,5,6,7,8,9,10],
       "y":[28.4, 44.1, 57.2, 68.8,67.4, 82.0, 103.0, 114.6, 138.3, 147.6],
       "x_1":[1,2,4,4,5,6,7,7,9,"Hola"]} 

In [ ]:
Data = pd.DataFrame(Dic) 

In [ ]:
valores = np.array([2,3]) ; valores

array([2, 3])

In [ ]:
Modelo = Regresion(Data, "y", intercepto= True)

Hay un error, el Data Frame tiene datos no numericos
